### ISSUE TITLE
CircleCI systemd (centos7/xenial) container is not operational

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2-packages#31]
https://discuss.circleci.com/t/docker-with-centos7-systemd-container/885

**Comment by dennybaa** [comment]
well we know. cleaning the issue board though!

**Comment by armab** [comment]
This is still an issue that someone will probably hit and I think it's better to keep it for informational purposes rather then closing it, so someone won't open duplicate.

I guess we can gather more information about possible infra limitations users can face depending on environment: https://github.com/StackStorm/st2-packages/issues/154 and keep more useful info in this one.

**Comment by dennybaa** [comment]
just pollution, no outcome.

**Comment by armab** [comment]
What I mean - we're not only 2 guys here ;)

**Comment by dennybaa** [comment]
I mean pollution is pollution, if it pops up again - okay, if not keeping it for grandsons... ) Hoping they will read it one day) Well it can be named as pollution, ambiguous pre-caution you can find tons of things to name this useless kind of tickets.

Well if you forgot there's such thing like github search https://github.com/StackStorm/st2-packages/search?q=systemd&type=Issues&utf8=%E2%9C%93,  usually people use it dig through  problem first and not trying to read through the whole list which is the on-deck...

@armab Don't pollute, keep things clean and simple...

**Comment by armab** [comment]
@dennybaa closing this issue is kind of [hiding the dust under the rug](https://github.com/auchenberg/volkswagen).

Grandsons? We already had valid report: `Build fails for EL7`: https://github.com/StackStorm/st2-packages/issues/154
Which is exactly 100% the same infra limitation which exists.

Closed issue usually means `resolved`.
If we keep it open - it means `known`. And that's much useful.

**Comment by dennybaa** [comment]
What are you talking about...

1. #154 what connection with this issue? It's absolutely different issue, what infra?
2. **Can you technically fix it**? I.e. implement startup of systemd containers on Circle CI. If yes please reopen and solve it indeed.
3. If you can not do the 2 (^^), what's you goal to keep it visible? 

> Closed issue usually means resolved.
Absolutely not... Haven't you met *wontfix* in whatever projects?

**Comment by armab** [comment]
- Q: What these 2 issues have in common?
- A: centos7 not running properly


1.) You can't run Docker with systemd under Windows and MacOS X and probably somewhere else because of infra limitation (that issue #154)
2.) You can't run Docker with systemd under CircleCI because of security limitation (this issue #31)

---

Because of that, we should keep more info in one issue about `docker` + `centos7` + `systemd`.
So users won't loose time and could discover if they're just running docker for centos7 in a wrong way or it's their infra-related problem.

^^ This is a valid case.

**Comment by dennybaa** [comment]
1) Please first, read again #154 ...

> Errno::ECONNREFUSED: Connection refused - connect(2) for "centos7test" port 22
/root/st2-packages/rake/build/upload_checkout.rake:18:in `block (5 levels) in <top (required)>'
/root/st2-packages/rake/remote.rb:72:in `instance_exec'

If you don't know the issue please do not invent... That happened because sshd couldn't be started by systemd inside that container. **On linux, on docker (not lxc)**.

It happens on linux, and you are talking about MacOS and Windows. It happens on my linux host same as it happened on that guys host. **The fix was to enable privileged mode**. And you are talking about 100% same infra, which is not even close. There was neither macosx nor windows, and not even circle ci (which is docker-lxc and blocks cgroup volumes pass trough)...

_So no outcome, won't be fixed, issue can be searched (as systemd or circleci tag and more others)._

> So users won't loose time and could discover if they're just running docker for centos7 in a wrong way or it's their infra-related problem.

Users won't loose while it's searchable. My regrets to those who want to loose time reading through the whole list of bugs (our list is considerably small, but it will grow if we keep following good intentions like this :)
The last one thing if you'd like to reopen, please do it, i'm not going to bring more points.

**Comment by armab** [comment]
> That happened because sshd couldn't be started by systemd inside that container

Agree here. And that's exactly what all these issues have in common: 
- `docker`
- `systemd`
- `centos7`

Can you agree or deny that fact?

----

> The fix was to enable privileged mode 

No, at least you think so without agreement from the user.

At the moment of posting - it wasn't the reason. Because we both could use old docker-compose and centos7 without any `privileged` modes. What you're talking about with mode is probably recent changes.

**Comment by dennybaa** [comment]
> Can you agree or deny that fact?

Why do you so _severely_ want me to agree or disagree with you?  :) My points on this issue where not about the fact you are mentioning, I hope you understand)

> No, at least you think so without agreement from the user.

Dude, why do you even talk about this? I believe I fixed his particular and our also issue, that seems enough for me) If it's not enough for you please feel free try to reproduce it and reopen then, np)

read #154, the last comment last sentence.

> Feel free to re-open, meanwhile closing it.
