### ISSUE TITLE
Add deb/rpm Conflicts after migrating to Mongo 3.x

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#324]
Add `Conflicts: mongodb-server (<< 3.0.0)`

Like https://github.com/StackStorm/st2chatops/pull/46 this will save from mistakes when user installs wrong Mongo version, so the new `st2` package conflicts with Mongo less then `3.x`.

The possible problem could be in the case when on the same box _older_ `Mongo` is already installed for different purposes, but `st2` is configured to use remote mongodb.
But hopefully, this condition should be rare, since we usually assume that st2 is installed on dedicated/clean machine.

**Comment by Kami** [comment]
Thanks for the feedback.

I'm not sure if that's the best idea, since as you mentioned, we will only start using 3.2 for new installations. For old / existing installations we will still support 2.x and won't force users to perform a migration (it's up to them to migrate if they want to utilize MongoDB improvements).

So having said that, I don't think it's a best idea to add this to the package metadata since it would cause issues with existing installations.

**Comment by Kami** [comment]
Thanks for the feedback.

I'm not sure if that's the best idea, since as you mentioned, we will only start using 3.2 for new installations. For old / existing installations we will still support 2.x and won't force users to perform a migration (it's up to them to migrate if they want to utilize MongoDB improvements).

So having said that, I don't think it's a best idea to add this to the package metadata since it would cause issues with existing installations.

**Comment by armab** [comment]
Since `st2-packages` is branch-versioned, this could be included only starting from `1.6+`.

Also, is there backwards compatibility? Can st2 `1.6` work with older `2.x` Mongo?

**Comment by Kami** [comment]
@armab Yes, latest st2 code in master which will become v1.6 still works with MongoDB 2.x so there is no big rush for this change :)

So perhaps we can add this change later, maybe in v1.7 or similar. This way we don't "force" existing users to migrate to 3.x since migration requires some efforts and down time.

**Comment by armab** [comment]
> still works with MongoDB 2.x

:+1:
