### ISSUE TITLE
st2 package should depend on ssh

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#379]
`st2` (and `st2mistral`?) `deb` and `rpm` packages should depend on `ssh`.

> This is actually real issue reported in community when user had no `/bin/ssh` (IDK how it's possible though).

**Comment by LindsayHill** [comment]
I've seen a related problem where users don't have openssh-server installed/enabled. If they run the installer script, verification fails (because `core.remote` with `host=127.0.0.1` fails).

I almost always install with a remote VM, but it seems that lots of people use very minimal install local VM & do install via console
