### ISSUE TITLE
On upgrade, st2.conf is replaced on Ubuntu

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2-packages#412]
* ubuntu
* st2 v2.1
* st2 package

Issue details
On a st2 system installed via the script https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh, upgrading the st2 package per https://docs.stackstorm.com/install/upgrades.html by running `sudo apt-get install --only-upgrade st2` will backup /etc/st2/st2.conf to /etc/st2/st2.conf.dpkg-old and replace w/ a new st2.conf. This clears the auth, DB creds, and datastore encryption key path in the original config.

**Comment by armab** [comment]
Normally packaging is smart enough to handle config change differencies.

From [Debian Policy](https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html):
> - If neither the user nor the package maintainer has changed the file, it is left alone.
> - If one or the other has changed their version, then the changed version is preferred - i.e., if the user edits their file, but the package maintainer doesn't ship a different version, the user's changes will stay, silently, but if the maintainer ships a new version and the user hasn't edited it the new version will be installed (with an informative message).
> - If both have changed their version the user is prompted about the problem and must resolve the differences themselves. 


We got the state when both user's config and upstream package config is changed. In this scenario default behavior is that `apt-get` switches into interactive mode asking what to do next, with default behavior to persist user's config.
This happens in transition between `2.1` and `2.2`, since we changed [`st2.package.conf`](https://github.com/StackStorm/st2/blob/master/conf/st2.package.conf) (28 days ago).

Details:

## Install older st2 `2.1dev`
```sh
curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password=st2admin --unstable --version=2.1dev
```
So when researching this I tried several upgrading scenarios on a clean `Ubuntu14` Vagrant VM (`ubuntu/trusty64`).
## Upgrade to never st2 `2.2.dev`
#### 1) `sudo apt-get upgrade`
#### 2) `sudo apt-get --assume-yes --force-yes upgrade`
#### 3) `sudo apt-get install --only-upgrade st2`
#### 4) `sudo apt-get install --assume-yes --force-yes --only-upgrade st2`

For all `4` examples I got the same behavior when user is interactively asked for input, even with: `--assume-yes --force-yes`:
```sh
The following packages will be upgraded:
  st2
1 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
Need to get 20.2 MB of archives.
After this operation, 13.1 MB disk space will be freed.
Fetched 20.2 MB in 11s (1,802 kB/s)
(Reading database ... 107570 files and directories currently installed.)
Preparing to unpack .../st2_2.2dev-61_amd64.deb ...
Unpacking st2 (2.2dev-61) over (2.1dev-116) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up st2 (2.2dev-61) ...

Configuration file '/etc/st2/st2.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** st2.conf (Y/I/N/O/D/Z) [default=N] ? [Enter]
```

Note that default behavior for `st2.conf` is: 
> `N or O  : keep your currently-installed version`

Eg. changed by user `st2.conf` **is preserved** by default, unless you provide different answer.

#### Automatic way
So since the change is significant, `apt-get` asks for user input to decide what to do next.
But you can still override this behavior by providing apt options.
```sh
sudo apt-get install --option Dpkg::Options::="--force-confold" --only-upgrade  st2
```
with the following output:
```sh
The following packages will be upgraded:
  st2
1 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
Preparing to unpack .../st2_2.2dev-61_amd64.deb ...
Unpacking st2 (2.2dev-61) over (2.1dev-116) ...
Setting up st2 (2.2dev-61) ...

Configuration file '/etc/st2/st2.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Using current old file as you requested.
```


### Conclusion
Everything is good, we're safe. `st2.conf` is not replaced when both user and upstream config is changed. `apt-get` gives priority to user's config by default.

**Comment by armab** [comment]
As discussed, it might be confusing that default option from `dpkg` is `N`:
```
Configuration file '/etc/st2/st2.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** st2.conf (Y/I/N/O/D/Z) [default=N] ? [Enter]
```
while users developed the habit to answer `Y` for everything. In this case it will do the opposite, - write package's config files instead of user's.

**Comment by Kami** [comment]
@armab Nice work and thanks for clarifying this.
