### ISSUE TITLE
Run mistral-db-manage upgrade head and populate on package upgrade

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2-packages#421]
Please refer to this PR https://github.com/StackStorm/st2docs/pull/392 for details. Basically if the mistral and mistral-api services are started first, the mistral-db-manage commands may fail. The suggestion is to include these commands in the package post install. Under normal circumstances, these commands are idempotent. Important note that these commands require the database connection setting in /etc/mistral/mistral.conf to work. Also, if any error should occur on package upgrade, the user should be made aware.

**Comment by armab** [comment]
My concern is that common practice is to avoid something like that during the `deb/rpm` package install/upgrade.
The main reason is that package Install/Upgrade should not be blocked or stopped or broken because of external resource like DB connection or misconfigured `mistral.conf` or phase of the moon.
So here we should be very careful to avoid any dangerous practices which could bring bad surprises to users.

I checked today a bit how `st2mistral` package behaves/installed/upgraded and played with `mistral-db-manage` command.

### Approach 1

I would like us to avoid blindly running `upgrade head` + `populate` on every package version/revision upgrade, but instead try to rely on `mistral-db-manage current` (which shows the current state) and if there is really DB migration available - run the commands.

Saying that, my guess is that we can do "best effort" with the following during package upgrade:

- `mistral stop`
- `mistral-db-manage --config-file /etc/mistral/mistral.conf current`
  - ^^ check if DB upgrade available
     - `mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head`
       - `mistral-db-manage --config-file /etc/mistral/mistral.conf populate`
- `mistral start`

1) Don't block package upgrade if any of DB commands failed (`|| /bin/true`)
2) If failed, don't run next migration command
3) If failed, print a clear message to stderr (as @m4dcoder noted)

The bad: you could upgrade package and miss failed mistral upgrade because it's not blocking.
The bad: starting mistral service without an upgrade can result in broken DB schema

### Approach 2
First approach was to run upgrade in packaging itself.
But it can't save us from the cases when for example DB is re-initialized, `service mistral start` was ran without DB `upgrade`, which results in broken DB schema (as noted in https://github.com/StackStorm/st2docs/pull/392#discussion_r101507701) and so on roadblocks.

Another way is to handle if DB is up to date on invoking `service start`.
This will solve our problems, but its a bit of crazy idea and have another set of edge cases.

With that, 2 ways are possible: 
a) If migration available - don't start `mistral`, exit with error asking user to run DB migration manually
   - not a common practice, but safest way
   - shift responsibility to users to run the migration
   - could be unexpected if service is not started after the package upgrade

b) If migration available - run DB scripts automatically on `service mistral start`
   - the good: brings full automation for `st2mistral` migrations
   - the bad: unexpected behavior (?)
   - DB migration could take some time on big databases before services startup
     - in some cases can affect `service` status machinery (needs more technical research)
       - service is up, connection still not available

----

More opinions here are very appreciated, because so good intentions potentially could be an evil for users.
@m4dcoder @dzimine @lakshmi-kannan @Kami @LindsayHill @bigmstone  So how it feels for you as a user? Any edge cases? Anything else I'm missing?

And while both approaches could be dangerous if something goes wrong, I think we still should try automating it. It will bring us some good knowledge and experience before implementing full automated migration support in packaging for `StackStorm/st2`.

**Comment by s2ugimot** [comment]
I would like to vote on Approach 2 because as rpm/deb package upgrade is rather recommended method, it is not always the case, using docker container for example.

I'm managing my st2 server using my own built docker container with every st2 services in there, but when upgrading st2, It is done just replacing the container image with new st2 stack installed in it so I'll lose the chance to run those scripts if that is in post-install script of the packages.

**Comment by armab** [comment]
@s2ugimot Thanks, your feedback is very useful! Dockerized app is what we missed for sure in this upgrade story.

**Comment by shusugmt** [comment]
I just want to make sure that this is already implemented? At least with Ubuntu 14.04 `/etc/init/mistral.conf` contains `mistral-db-manage` command in it, which is exactly the strategy (b)

I'm not sure about other implementations (CentOS 6/7, Ubuntu 16.04) though.
