### ISSUE TITLE
st2web package

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#54]
[st2web](https://github.com/stackstorm/st2web) needs to be shipped as real package, as @jfryman noted here: https://github.com/StackStorm/discussions/issues/131

I'm not sure if the packaging codebase/logic should be included as part of `st2-packages` or [`st2web`](https://github.com/stackstorm/st2web) repos.

I'll just open it here to have some food for future thinking.

#### Info
* There are [acceptance Selenium tests](https://github.com/stackstorm/st2web#testing) for st2web
* [st2web](https://github.com/stackstorm/st2web) follows almost the same model with versioned branches as `st2` repo, eg. `v1.1`, `v1.2` for stable, `master` for unstable.

#### For sure:
* `st2web` package creation should be triggered when there were new changes in [`st2web`](https://github.com/stackstorm/st2web) repo
* We need to upload st2web packages to Bintray (stable for `vX.Y.Z` branch, unstable for `master`)

#### Questions:
* Is Selenium/Acceptance testing included in StackStorm `staging` box pipeline (internal testing)?
* Do we need to upload st2web to Bintray `staging` repo or we can just upload directly to Bintray production repo?  (depends on previous Q)
* Do we need the same packaging architecture when building st2web package? (spinning Docker containers with different distros) - probably depends on packaging approach/software choosed.
* ...

**Comment by armab** [comment]
Also cc @emedvedev and @enykeev

**Comment by enykeev** [comment]
oh lol, we just've talked about it in slack =)

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450701275016682

**Comment by lakshmi-kannan** [comment]
I caught up on the discussion. I was thinking about packaging artifacts being in the source repo itself but this won't work for enterprise packages like st2flow. Instead of having them in source repo for some and for some outside, let's just be consistent and keep the packaging stuff outside. (circle.yml should probably be the only one inside the source repo). 

I'd for now use st2-packages as the single repo for packaging unless we find a valid reason to spread them out or it becomes easier to build by virtue of different packaging repos. 

Please leave the (Selenium) testing of st2web packages to st2cd. You can have rspec testing for packages (like you do for st2) in circle.

**Comment by enykeev** [comment]
Yeah, agree on both counts. Packaging specs should be in their own repo and we should not change how we test web components at that point.

**Comment by dennybaa** [comment]
@enykeev , @armab as you decide to use st2web/st2flow repos directly, get back here so we can close the issue.
Current vision, that packaging code for st2flow/st2web should be located there.

**Comment by armab** [comment]
Closed by https://github.com/StackStorm/st2web/pull/269
