### ISSUE TITLE
Install script attempts to restart non-existent st2workflowengine component

### ISSUE THREAD

**Issue by tcosprojects** [StackStorm/st2-packages#576]
OS: Ubuntu 16.04.4 LTS
StackStorm Version: st2 2.7.2, on Python 2.7
Installed with: install.sh, st2bootstrap-deb.sh

Using the quick install instructions, the following error occurs:

```
20180708T114925+0000 Error: Invalid component provided: st2workflowengine
20180708T114925+0000
20180708T114925+0000 Usage: st2ctl {start, stop, restart, status}
20180708T114925+0000
20180708T114925+0000 Usage: st2ctl {restart-component}
20180708T114925+0000 positional arguments:
20180708T114925+0000   component           Name of the st2 service to restart.
20180708T114925+0000                       st2actionrunner st2api st2stream st2auth st2garbagecollector st2notifier st2resultstracker st2rulesengine st2sensorcontainer st2chatops mistral
20180708T114925+0000
20180708T114925+0000 Usage: st2ctl {reopen-log-files}
20180708T114925+0000 positional arguments:
20180708T114925+0000   component           Name of the st2 service to reopen the log files for.
20180708T114925+0000                       st2actionrunner st2api st2stream st2auth st2garbagecollector st2notifier st2resultstracker st2rulesengine st2sensorcontainer st2chatops
20180708T114925+0000
20180708T114925+0000 Usage: st2ctl {reload, clean}
20180708T114925+0000 optional arguments:
20180708T114925+0000   --register-all                Register all.
20180708T114925+0000   --register-triggers           Register all triggers.
20180708T114925+0000   --register-sensors            Register all sensors.
20180708T114925+0000   --register-rules              Register all rules.
20180708T114925+0000   --register-runners            Register all runners.
20180708T114925+0000   --register-actions            Register all actions.
20180708T114925+0000   --register-aliases            Register all aliases.
20180708T114925+0000   --register-policies           Register all policies.
20180708T114925+0000   --register-configs            Register all configuration files.
20180708T114925+0000   --register-setup-virtualenvs  Create Python virtual environments for all the registered packs.
20180708T114925+0000   --register-fail-on-failure    Exit with non-zero if some resource registration fails. Deprecated. This is now a default behavior.
20180708T114925+0000   --register-no-fail-on-failure Don't exit with non-zero if some resource registration fails.
20180708T114925+0000   --verbose                     Output additional debug and informational messages.
20180708T114925+0000
20180708T114925+0000 Most commands require elevated privileges.
20180708T114925+0000 ############### ERROR ###############
20180708T114925+0000 # Failed on Generate symmetric crypto key for datastore #
20180708T114925+0000 #####################################
```

**Comment by nmaludy** [comment]
I just ran into this too. Looks like a PR got merged into packaging a little early. It's attempting to reference the new workflow service that hasn't been merged into stable yet.

I think if you install from unstable branch, it _should_ work (trying it now myself):
```
curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --unstable --user=st2admin --password=xxx
```


@armab any better way we could "stage" the unstable changes, maybe an `unstable` or `develop` branch or something?

**Comment by nmaludy** [comment]
@tcosprojects just an update, passing in `--unstable` worked!

Looks like the offending commits happened 2 days ago https://github.com/StackStorm/st2-packages/commit/7afffd8370de934c08515c93828d9c883994349b (FYI @Kami )

**Comment by Kami** [comment]
Thanks for reporting this.

It's an issue with our release workflow - https://github.com/StackStorm/st2-packages/commit/cc7a385f31beff0a806eaf98bf0834deafc775d1

This change should be made at the very end when we promote packages to production (aka v2.7 st2-packages branch should be used until v2.8 release is actually released).

**Comment by Kami** [comment]
Thanks again for reporting this.

https://github.com/StackStorm/st2-packages/pull/577 should resolve this for the time beginning. And in the future / long term we need to make one of the changes mentioned above (either link to stable version in stable docs or make that change in st2-packages repo as a very last step in our release workflow).

**Comment by Kami** [comment]
/cc @enykeev @lakshmi-kannan^ we will likely encounter similar issue with v2.9 when we introduce new timer engine service (or at some other point in the future when st2-packages version branch requires backward incompatible changes).

We should decide what approach to go with:

1) Update our release workflow to set `BRANCH=` variable in st2-packages repo as part of last step in our release workflow.

Right now we do it as part of `st2_prep_release` action which is too early since it means installer script linked in the docs will start consuming st2-packages "to be released" branch before release is fully finalized.

2) Update documentation stable version to always link to stable branch version of st2-packages repo instead of master - https://docs.stackstorm.com/install/index.html.

I believe we did this at some point in the past, but then we introduced nginx and redirect to avoid cert issues on RHEL (I think that's not relevant anymore though so we can safely link directly to github).

Only potential downside of this approach is that if a user visits documentation for older version of StackStorm, we will link to the installer script for that version. Some could even argue that's the correct approach and right thing to do.

Similar thing could also be achieved if we updated docs to still link to master but pass `--version=<stable version>` to the installer script (this still has more edge cases though(.

**Comment by armab** [comment]
Both `#1` and `#2` sounds like good improvements, independent on each other :+1: 

Wondering if changing `#1` will affect somehow our release testing workflows, making assumptions that the new updated version is already available/live. Likely will pop up other corner cases somewhere.

**Comment by Kami** [comment]
@armab 

> Wondering if changing #1 will affect somehow our release testing workflows, making assumptions that the new updated version is already available/live. Likely will pop up other corner cases somewhere.

Yeah, that's was my main concern - who knows what workflows depend on that variable being set at that stage.

In theory, this shouldn't be an issue because same end result can be achieved using --version / --force-branch flags in our workflows. Main problem might just be identifying those workflows (if there are any).
