### ISSUE TITLE
stable/unstable paradigm for package repos (rhel direct package link)

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2-packages#85]
I find it quite misleading to have stable/unstable on top of `staging` and `stable (just top ones el6/el7)` repos. At least for centos, the current implemented approach works not in sync with standards used by rhel-camp or it might be bintray works bad.

Anyway the issue on the face, if you get package installation directly, it doesn't work due to paths mangling inside the repository.
```
wget https://bintray.com/stackstorm/el7_staging/rpm -O bintray-stackstorm-el7_staging.repo
```

I don't know further details, but seems far from being right(

@armab , @lakshmi-kannan

**Comment by dennybaa** [comment]
further I've noticed also, that if i'm add both stable and unstable onto the rhel system. There's no way to install mistral((( It doesn't work.

**Comment by armab** [comment]
Example for unstable: `/etc/yum.repos.d/StackStorm-el7_staging-unstable.repo`
```ini
[StackStorm-el7_staging-unstable]
name=StackStorm-el7_staging-unstable
baseurl=https://dl.bintray.com/stackstorm/el7_staging/unstable
enabled=1
```
```sh
yum install st2bundle
```

**Comment by armab** [comment]
if you want `mistral` - add both `stable` and `unstable` repos.
And `mistral` will be installed from `stable`, same approach as `apt-get` see: https://stackstorm.slack.com/archives/stackstorm/p1453136588026473

**Comment by dennybaa** [comment]
> Anyway the issue on the face, if you get package installation directly, it doesn't work due to paths mangling inside the repository.
> ```
wget https://bintray.com/stackstorm/el7_staging/rpm -O bintray-stackstorm-el7_staging.repo
```


**Direct repo links do not work**. Installation using the following repo shortcut is not working, but **ONLY** the full file substitution as you show yourself.
It might be due to:
* buggy bintray.
* wrong publishing in bintray.
* wrong paradigm of using rhel repos.

**Comment by armab** [comment]
```
https://dl.bintray.com/stackstorm/el7_staging/unstable
https://dl.bintray.com/stackstorm/el7_staging/stable
```
as endpoints for `stable`/`unstable` is working as expected, see discussion: https://github.com/StackStorm/discussions/issues/130 behind it.


Technically, directory tree in example above is the same as: 
https://dl.fedoraproject.org/pub/epel/6/x86_64/
https://dl.fedoraproject.org/pub/epel/7/x86_64/
which is broadly used.
If you add `https://dl.fedoraproject.org/pub/epel/` as endpoint - it won't work too, because there is no `repodata/repomd.xml` in that dir.

I don't see anything wrong here.

---
So putting everything together:
* This endpoint: https://dl.fedoraproject.org/pub/epel/6/x86_64/ is OK because it contains: `repodata/repomd.xml`
* This endpoint: https://dl.fedoraproject.org/pub/epel/7/x86_64/ is OK because it contains `repodata/repomd.xml`

* This endpoint: https://dl.bintray.com/stackstorm/el7_staging/unstable is OK because of `repodata/repomd.xml` in it.
* This endpoint: https://dl.bintray.com/stackstorm/el7_staging/stable is OK because of `repodata/repomd.xml` in it.

Bintray just a bit confusing with our case by giving that single installation file. Probably what they do is "best guess". BTW I remember @enykeev was confused too with that file.

**Comment by dennybaa** [comment]
Uhf, I see( Thank you for explanation!

**Comment by lakshmi-kannan** [comment]
:+1: to @armab
